#!/usr/bin/env spang2
# @endpoint https://orth.dbcls.jp/sparql-test
# @option --time

PREFIX cao: <http://chip-atlas.org/ontology/>

SELECT (COUNT(?s) AS ?count)
WHERE {
  ?s a cao:PutativeRegulation ;
     cao:score10k ?score .
}
