#!/usr/bin/env spang2
# @endpoint https://orth.dbcls.jp/sparql-test
# @option --time -va

PREFIX cao: <http://chip-atlas.org/ontology/>

SELECT ?tf (COUNT(DISTINCT ?target) AS ?count_target)
WHERE {
  ?s a cao:PutativeRegulation ;
     cao:hasTarget ?target ;
     cao:hasTF ?tf .
}
ORDER BY DESC(?count_target) ?tf
