#!/usr/bin/env spang2
# @endpoint https://orth.dbcls.jp/sparql-test
# @option --time -va

PREFIX cao: <http://chip-atlas.org/ontology/>

SELECT ?tf (COUNT(DISTINCT ?target_gene) AS ?target_gene_counts)
WHERE {
  ?s a cao:PutativeRegulation ;
     cao:hasTF ?tf ;
     cao:score5k ?score ;
     cao:hasTargetGene ?target_gene .
}
ORDER BY DESC(?target_gene_counts) ?tf
